//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nada.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nada.Globalization.NewKeys", typeof(NewKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Integrated NTD Database was developed by RTI International under the ENVISION project with funding from the United States Agency for International Development in collaboration with the World Health Organization (WHO) and its regional offices (AFR, SEAR, WPR), the African Programme for Onchocerciasis Control and the Centre for Neglected Tropical Diseases.
        ///
        ///The Integrated NTD Database was developed by Iota Ink:
        ///Jennifer Einberg, Project Manager; Eric Olson, Developer; 
        ///Jennifer Fox, Graphic Designer;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutDisclaimer {
            get {
                return ResourceManager.GetString("AboutDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Integrated NTD Database.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative units.
        /// </summary>
        public static string AdministrativeUnits {
            get {
                return ResourceManager.GetString("AdministrativeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative unit above level you are adding..
        /// </summary>
        public static string AdminUnitParent {
            get {
                return ResourceManager.GetString("AdminUnitParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peri-rural.
        /// </summary>
        public static string AdminUnitPeriRural {
            get {
                return ResourceManager.GetString("AdminUnitPeriRural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rural.
        /// </summary>
        public static string AdminUnitRural {
            get {
                return ResourceManager.GetString("AdminUnitRural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative units.
        /// </summary>
        public static string AdminUnits {
            get {
                return ResourceManager.GetString("AdminUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative units surveyed.
        /// </summary>
        public static string AdminUnitsSurveyed {
            get {
                return ResourceManager.GetString("AdminUnitsSurveyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urban.
        /// </summary>
        public static string AdminUnitUrban {
            get {
                return ResourceManager.GetString("AdminUnitUrban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated NTD Database.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar year.
        /// </summary>
        public static string CalendarYear {
            get {
                return ResourceManager.GetString("CalendarYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string CmBudget {
            get {
                return ResourceManager.GetString("CmBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proportion of funds allocated to NTDs in the National Health Sector Budget (%).
        /// </summary>
        public static string CmBudgetProportion {
            get {
                return ResourceManager.GetString("CmBudgetProportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Statistics.
        /// </summary>
        public static string CountryStatistics {
            get {
                return ResourceManager.GetString("CountryStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom year.
        /// </summary>
        public static string CustomYear {
            get {
                return ResourceManager.GetString("CustomYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please revert to the most recent backup of your database: .
        /// </summary>
        public static string DatabaseScriptBackup {
            get {
                return ResourceManager.GetString("DatabaseScriptBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achieved criteria for stopping district-level MDA for trachoma?.
        /// </summary>
        public static string DDTraAchievedCriteria {
            get {
                return ResourceManager.GetString("DDTraAchievedCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is all or part of the area under surveillance for TF?.
        /// </summary>
        public static string DDTraAllTf {
            get {
                return ResourceManager.GetString("DDTraAllTf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is all or part of the area under surveillance for TT?.
        /// </summary>
        public static string DDTraAllTt {
            get {
                return ResourceManager.GetString("DDTraAllTt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current level of implementation (district or sub-district).
        /// </summary>
        public static string DDTraLevelCurrent {
            get {
                return ResourceManager.GetString("DDTraLevelCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of implementation recommended based on WHO guidelines (district or sub-district).
        /// </summary>
        public static string DDTraLevelRecWho {
            get {
                return ResourceManager.GetString("DDTraLevelRecWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trichiasis backlog.
        /// </summary>
        public static string DDTraTrichiasisBacklog {
            get {
                return ResourceManager.GetString("DDTraTrichiasisBacklog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year achieved UIG-A.
        /// </summary>
        public static string DDTraYearAchievedUiga {
            get {
                return ResourceManager.GetString("DDTraYearAchievedUiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of planned impact assessment.
        /// </summary>
        public static string DDTraYearDeterminedThatAchievedCriteriaF {
            get {
                return ResourceManager.GetString("DDTraYearDeterminedThatAchievedCriteriaF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of planned trachoma impact survey.
        /// </summary>
        public static string DDTraYearOfPlannedTrachomaImpactSurvey {
            get {
                return ResourceManager.GetString("DDTraYearOfPlannedTrachomaImpactSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of persons living in areas that have achieved the criteria for stopping PC.
        /// </summary>
        public static string EliminationLiving {
            get {
                return ResourceManager.GetString("EliminationLiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the Integrated NTD Database?.
        /// </summary>
        public static string ExitWarning {
            get {
                return ResourceManager.GetString("ExitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting Application.
        /// </summary>
        public static string ExitWarningTitle {
            get {
                return ResourceManager.GetString("ExitWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC epidemiologial data reporting form.
        /// </summary>
        public static string ExportsPcEpiDataForm {
            get {
                return ResourceManager.GetString("ExportsPcEpiDataForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecological zone description, if applicable.
        /// </summary>
        public static string EzName {
            get {
                return ResourceManager.GetString("EzName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demography import.
        /// </summary>
        public static string ImportDemo {
            get {
                return ResourceManager.GetString("ImportDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important note: Survey imports only work for surveys that take place in just one administrative unit at a time. If any of your surveys take place in more than one administrative unit at a time (for example, an Ecological Zone spanning multiple districts), those surveys need to be entered directly into the forms. They will not record properly if entered here in imports..
        /// </summary>
        public static string ImportSurveyWarning {
            get {
                return ResourceManager.GetString("ImportSurveyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals examined for Hydrocele.
        /// </summary>
        public static string LFMapSurExaminedHydro1 {
            get {
                return ResourceManager.GetString("LFMapSurExaminedHydro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals examined for Lymphoedema.
        /// </summary>
        public static string LFMapSurExaminedLympho {
            get {
                return ResourceManager.GetString("LFMapSurExaminedLympho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals positive for Hydrocele.
        /// </summary>
        public static string LFMapSurNumberOfCasesOfHydrocele {
            get {
                return ResourceManager.GetString("LFMapSurNumberOfCasesOfHydrocele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals positive for Lymphoedema.
        /// </summary>
        public static string LFMapSurNumberOfCasesOfLymphoedema {
            get {
                return ResourceManager.GetString("LFMapSurNumberOfCasesOfLymphoedema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of females examined for Mf/Ag.
        /// </summary>
        public static string LFMapSurNumberOfFemalesExamined {
            get {
                return ResourceManager.GetString("LFMapSurNumberOfFemalesExamined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of females positive for Mf/Ag.
        /// </summary>
        public static string LFMapSurNumberOfFemalesPositive {
            get {
                return ResourceManager.GetString("LFMapSurNumberOfFemalesPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals examined for Mf/Ag.
        /// </summary>
        public static string LFMapSurNumberOfIndividualsExamined {
            get {
                return ResourceManager.GetString("LFMapSurNumberOfIndividualsExamined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals positive for Mf/Ag.
        /// </summary>
        public static string LFMapSurNumberOfIndividualsPositive {
            get {
                return ResourceManager.GetString("LFMapSurNumberOfIndividualsPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of males examined for Mf/Ag.
        /// </summary>
        public static string LFMapSurNumberOfMalesExamined {
            get {
                return ResourceManager.GetString("LFMapSurNumberOfMalesExamined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of males positive for Mf/Ag.
        /// </summary>
        public static string LFMapSurNumberOfMalesPositive {
            get {
                return ResourceManager.GetString("LFMapSurNumberOfMalesPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals examined for Hydrocele.
        /// </summary>
        public static string LFSurExaminedHydro {
            get {
                return ResourceManager.GetString("LFSurExaminedHydro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals examined for Lymphoedema.
        /// </summary>
        public static string LFSurExaminedLympho {
            get {
                return ResourceManager.GetString("LFSurExaminedLympho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals examined for Mf/Ag.
        /// </summary>
        public static string LFSurNumberOfIndividualsExamined {
            get {
                return ResourceManager.GetString("LFSurNumberOfIndividualsExamined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals positive for Mf/Ag.
        /// </summary>
        public static string LFSurNumberOfIndividualsPositive {
            get {
                return ResourceManager.GetString("LFSurNumberOfIndividualsPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals positive for Hydrocele.
        /// </summary>
        public static string LFSurPosHydro {
            get {
                return ResourceManager.GetString("LFSurPosHydro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals positive for Lymphoedema.
        /// </summary>
        public static string LFSurPosLympho {
            get {
                return ResourceManager.GetString("LFSurPosLympho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete administrative units.
        /// </summary>
        public static string MenuDeleteAdminLevel {
            get {
                return ResourceManager.GetString("MenuDeleteAdminLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge administrative units.
        /// </summary>
        public static string MenuMergeDistrict {
            get {
                return ResourceManager.GetString("MenuMergeDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add administrative units.
        /// </summary>
        public static string MenuNewAdminLevel {
            get {
                return ResourceManager.GetString("MenuNewAdminLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add demography for a new year.
        /// </summary>
        public static string MenuNewYearDemo {
            get {
                return ResourceManager.GetString("MenuNewYearDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add disease distribution for a new year.
        /// </summary>
        public static string MenuNewYearDistro {
            get {
                return ResourceManager.GetString("MenuNewYearDistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split/combine administrative units.
        /// </summary>
        public static string MenuSplitCombineDistrict {
            get {
                return ResourceManager.GetString("MenuSplitCombineDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split administrative units.
        /// </summary>
        public static string MenuSplitDistrict {
            get {
                return ResourceManager.GetString("MenuSplitDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template for the Integrated NTD Database was developed by RTI International under the ENVISION project with funding from the United States Agency for International Development in cooperation with the World Health Organization (WHO) and its regional offices, the African Programme for Onchocerciasis Control and the Centre for Neglected Tropical Diseases..
        /// </summary>
        public static string NadaIntro {
            get {
                return ResourceManager.GetString("NadaIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated NTD Database.
        /// </summary>
        public static string NationalDatabaseTemplate {
            get {
                return ResourceManager.GetString("NationalDatabaseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New year updates.
        /// </summary>
        public static string NewYearUpdates {
            get {
                return ResourceManager.GetString("NewYearUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of mapping.
        /// </summary>
        public static string OnchoMapSurTypeOfMapping {
            get {
                return ResourceManager.GetString("OnchoMapSurTypeOfMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Biting Rates (ABR).
        /// </summary>
        public static string OnchoSurEntAbr {
            get {
                return ResourceManager.GetString("OnchoSurEntAbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Transmission Potential (ATP) (the average number of infective stage parasites an individual is exposed to in a year).
        /// </summary>
        public static string OnchoSurEntAtp {
            get {
                return ResourceManager.GetString("OnchoSurEntAtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected infection rate (PCR) - per 1,000 parous flies.
        /// </summary>
        public static string OnchoSurEntCorrectedInfectionRatePcr {
            get {
                return ResourceManager.GetString("OnchoSurEntCorrectedInfectionRatePcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infection rate (Dissection) - per 1,000 parous flies.
        /// </summary>
        public static string OnchoSurEntInfectionRateDissection {
            get {
                return ResourceManager.GetString("OnchoSurEntInfectionRateDissection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Biting Rates.
        /// </summary>
        public static string OnchoSurEntMbr {
            get {
                return ResourceManager.GetString("OnchoSurEntMbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Transmission Potential.
        /// </summary>
        public static string OnchoSurEntMtp {
            get {
                return ResourceManager.GetString("OnchoSurEntMtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomic identification - Cytotaxonomy (Chromosomal).
        /// </summary>
        public static string OnchoSurEntTaxoCyto {
            get {
                return ResourceManager.GetString("OnchoSurEntTaxoCyto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest.
        /// </summary>
        public static string OnchoSurEntTaxoForest {
            get {
                return ResourceManager.GetString("OnchoSurEntTaxoForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest and Savannah.
        /// </summary>
        public static string OnchoSurEntTaxoForestSav {
            get {
                return ResourceManager.GetString("OnchoSurEntTaxoForestSav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomic identification - Morphology.
        /// </summary>
        public static string OnchoSurEntTaxonomic {
            get {
                return ResourceManager.GetString("OnchoSurEntTaxonomic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savannah.
        /// </summary>
        public static string OnchoSurEntTaxoSavannah {
            get {
                return ResourceManager.GetString("OnchoSurEntTaxoSavannah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Technique.
        /// </summary>
        public static string OnchoSurEntTestTech {
            get {
                return ResourceManager.GetString("OnchoSurEntTestTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromosomal identification.
        /// </summary>
        public static string OnchoSurEntTestTechChromo {
            get {
                return ResourceManager.GetString("OnchoSurEntTestTechChromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissection.
        /// </summary>
        public static string OnchoSurEntTestTechDiss {
            get {
                return ResourceManager.GetString("OnchoSurEntTestTechDiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCR Pool Screening.
        /// </summary>
        public static string OnchoSurEntTestTechPcr {
            get {
                return ResourceManager.GetString("OnchoSurEntTestTechPcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapping.
        /// </summary>
        public static string OnchoSurEntTestTechTrap {
            get {
                return ResourceManager.GetString("OnchoSurEntTestTechTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of mapping.
        /// </summary>
        public static string OnchoSurTypeOfMapping {
            get {
                return ResourceManager.GetString("OnchoSurTypeOfMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMO.
        /// </summary>
        public static string OnchoSurTypeRemo {
            get {
                return ResourceManager.GetString("OnchoSurTypeRemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delineation mapping.
        /// </summary>
        public static string OnchSurTypeDelineation {
            get {
                return ResourceManager.GetString("OnchSurTypeDelineation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a parent for the new administrative level that is of type: {0}.
        /// </summary>
        public static string ParentLevelMustBeSame {
            get {
                return ResourceManager.GetString("ParentLevelMustBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of total, # females treated for oncho.
        /// </summary>
        public static string PcIntvOfTotalFemalesOncho {
            get {
                return ResourceManager.GetString("PcIntvOfTotalFemalesOncho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of total, # females targeted  for oncho.
        /// </summary>
        public static string PcIntvOfTotalFemalesTargetedOncho {
            get {
                return ResourceManager.GetString("PcIntvOfTotalFemalesTargetedOncho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of total, # males treated for oncho.
        /// </summary>
        public static string PcIntvOfTotalMalesOncho {
            get {
                return ResourceManager.GetString("PcIntvOfTotalMalesOncho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of total, # males targeted for oncho.
        /// </summary>
        public static string PcIntvOfTotalMalesTargetedOncho {
            get {
                return ResourceManager.GetString("PcIntvOfTotalMalesTargetedOncho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zithromax POS.
        /// </summary>
        public static string PcIntvTraDrugPos {
            get {
                return ResourceManager.GetString("PcIntvTraDrugPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEO.
        /// </summary>
        public static string PcIntvTraDrugTeo {
            get {
                return ResourceManager.GetString("PcIntvTraDrugTeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zithromax Tablets.
        /// </summary>
        public static string PcIntvTraDrugZith {
            get {
                return ResourceManager.GetString("PcIntvTraDrugZith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the patient been evaluated at least 3 months post-surgery?.
        /// </summary>
        public static string PcIntvTsEval {
            get {
                return ResourceManager.GetString("PcIntvTsEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of females operated.
        /// </summary>
        public static string PcIntvTsNumFemales {
            get {
                return ResourceManager.GetString("PcIntvTsNumFemales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of complete kits available.
        /// </summary>
        public static string PcIntvTsNumKits {
            get {
                return ResourceManager.GetString("PcIntvTsNumKits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of males operated.
        /// </summary>
        public static string PcIntvTsNumMales {
            get {
                return ResourceManager.GetString("PcIntvTsNumMales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of people operated during reporting period.
        /// </summary>
        public static string PcIntvTsNumOperated {
            get {
                return ResourceManager.GetString("PcIntvTsNumOperated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of TT patients refusing surgery during reporting period.
        /// </summary>
        public static string PcIntvTsNumTt {
            get {
                return ResourceManager.GetString("PcIntvTsNumTt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of patients followed-up after surgery, what percentage were found with post-operative TT?.
        /// </summary>
        public static string PcIntvTsPercentWithPostOpTt {
            get {
                return ResourceManager.GetString("PcIntvTsPercentWithPostOpTt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what proportion of TT operations was TEO given postoperatively?.
        /// </summary>
        public static string PcIntvTsTtToTeo {
            get {
                return ResourceManager.GetString("PcIntvTsTtToTeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what proportion of TT operations was azithromycin given postoperatively?.
        /// </summary>
        public static string PcIntvTsTtToZithro {
            get {
                return ResourceManager.GetString("PcIntvTsTtToZithro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string PcTrainNew {
            get {
                return ResourceManager.GetString("PcTrainNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New or Refresher.
        /// </summary>
        public static string PcTrainNewOrRefresh {
            get {
                return ResourceManager.GetString("PcTrainNewOrRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresher.
        /// </summary>
        public static string PcTrainRefresher {
            get {
                return ResourceManager.GetString("PcTrainRefresher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string PcTrainUnknown {
            get {
                return ResourceManager.GetString("PcTrainUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redistricting event date.
        /// </summary>
        public static string RedistEventDate {
            get {
                return ResourceManager.GetString("RedistEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative level.
        /// </summary>
        public static string RedistLevel {
            get {
                return ResourceManager.GetString("RedistLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New administrative unit name.
        /// </summary>
        public static string RedistNewName {
            get {
                return ResourceManager.GetString("RedistNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New upper administrative unit name.
        /// </summary>
        public static string RedistNewParent {
            get {
                return ResourceManager.GetString("RedistNewParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population in new unit at time of redistricting.
        /// </summary>
        public static string RedistNewPop {
            get {
                return ResourceManager.GetString("RedistNewPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original administrative unit name.
        /// </summary>
        public static string RedistOrigName {
            get {
                return ResourceManager.GetString("RedistOrigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original upper administrative unit name.
        /// </summary>
        public static string RedistOrigParent {
            get {
                return ResourceManager.GetString("RedistOrigParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population at time of redistricting.
        /// </summary>
        public static string RedistOrigPop {
            get {
                return ResourceManager.GetString("RedistOrigPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only administrative units before redistricting.
        /// </summary>
        public static string RedistrictedAdminUnits {
            get {
                return ResourceManager.GetString("RedistrictedAdminUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redistricting Information.
        /// </summary>
        public static string RedistrictingInfo {
            get {
                return ResourceManager.GetString("RedistrictingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged from {0} on {1}.
        /// </summary>
        public static string RedistrictingMergeDesc {
            get {
                return ResourceManager.GetString("RedistrictingMergeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged into {0} on {1}.
        /// </summary>
        public static string RedistrictingMergeInto {
            get {
                return ResourceManager.GetString("RedistrictingMergeInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes about redistricting.
        /// </summary>
        public static string RedistrictingNotes {
            get {
                return ResourceManager.GetString("RedistrictingNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redistricting report.
        /// </summary>
        public static string RedistrictingReport {
            get {
                return ResourceManager.GetString("RedistrictingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split and combined from {0} on {1}.
        /// </summary>
        public static string RedistrictingSplitCombineDesc {
            get {
                return ResourceManager.GetString("RedistrictingSplitCombineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split and combined into {0} on {1}.
        /// </summary>
        public static string RedistrictingSplitCombineInto {
            get {
                return ResourceManager.GetString("RedistrictingSplitCombineInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split from {0} on {1}.
        /// </summary>
        public static string RedistrictingSplitDesc {
            get {
                return ResourceManager.GetString("RedistrictingSplitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split into {0} on {1}.
        /// </summary>
        public static string RedistrictingSplitInto {
            get {
                return ResourceManager.GetString("RedistrictingSplitInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string RedistrictTypeMerge {
            get {
                return ResourceManager.GetString("RedistrictTypeMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string RedistrictTypeSplit {
            get {
                return ResourceManager.GetString("RedistrictTypeSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split/combine.
        /// </summary>
        public static string RedistrictTypeSplitCombine {
            get {
                return ResourceManager.GetString("RedistrictTypeSplitCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of redistricting.
        /// </summary>
        public static string RedistType {
            get {
                return ResourceManager.GetString("RedistType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the errors and fix before continuing..
        /// </summary>
        public static string ReviewErrors {
            get {
                return ResourceManager.GetString("ReviewErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Reconcile.
        /// </summary>
        public static string RtiCantReconcile {
            get {
                return ResourceManager.GetString("RtiCantReconcile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTI Country Disease Workbook.
        /// </summary>
        public static string RtiCountryDiseaseWorkbook {
            get {
                return ResourceManager.GetString("RtiCountryDiseaseWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data completeness (%).
        /// </summary>
        public static string RtiDataCompleteness {
            get {
                return ResourceManager.GetString("RtiDataCompleteness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must match all units before continuing.
        /// </summary>
        public static string RtiErrorMustMatchAll {
            get {
                return ResourceManager.GetString("RtiErrorMustMatchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching country information from RTI system.
        /// </summary>
        public static string RtiFetchingTaskForceNames {
            get {
                return ResourceManager.GetString("RtiFetchingTaskForceNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match your units with the RTI system: {0}.
        /// </summary>
        public static string RtiMatchLevel {
            get {
                return ResourceManager.GetString("RtiMatchLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RtiName {
            get {
                return ResourceManager.GetString("RtiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RTI system has no data on that country, please double check your selection before continuing..
        /// </summary>
        public static string RtiNoData {
            get {
                return ResourceManager.GetString("RtiNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string RtiProjectName {
            get {
                return ResourceManager.GetString("RtiProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting level.
        /// </summary>
        public static string RtiReportingLevel {
            get {
                return ResourceManager.GetString("RtiReportingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting period.
        /// </summary>
        public static string RtiReportingPeriod {
            get {
                return ResourceManager.GetString("RtiReportingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Workbook for USAID reporting.
        /// </summary>
        public static string RtiReports {
            get {
                return ResourceManager.GetString("RtiReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip administrative unit reconciliation.
        /// </summary>
        public static string RtiSkipReconcile {
            get {
                return ResourceManager.GetString("RtiSkipReconcile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-partner name.
        /// </summary>
        public static string RtiSubPartnerName {
            get {
                return ResourceManager.GetString("RtiSubPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internet connection was not found. Please connect to the internet and try again, or check the box to skip reconciling your administrative units..
        /// </summary>
        public static string RtiTaskForceNoInternet {
            get {
                return ResourceManager.GetString("RtiTaskForceNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found when querying the RTI system, please contact support..
        /// </summary>
        public static string RtiTaskForceNoResults {
            get {
                return ResourceManager.GetString("RtiTaskForceNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string RtiTitle {
            get {
                return ResourceManager.GetString("RtiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total # districts submitted complete treatment report.
        /// </summary>
        public static string RtiTotalDistrictsComplete {
            get {
                return ResourceManager.GetString("RtiTotalDistrictsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total districts treated with USAID support.
        /// </summary>
        public static string RtiTotalDistrictsTreatedWithUsaid {
            get {
                return ResourceManager.GetString("RtiTotalDistrictsTreatedWithUsaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook questions.
        /// </summary>
        public static string RtiWorkbookQuestions {
            get {
                return ResourceManager.GetString("RtiWorkbookQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of workbook.
        /// </summary>
        public static string RtiYearOfWorkbook {
            get {
                return ResourceManager.GetString("RtiYearOfWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running….
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals positive for haematuria in urine.
        /// </summary>
        public static string SCHMapSurNumberOfIndividualsPositiveForH {
            get {
                return ResourceManager.GetString("SCHMapSurNumberOfIndividualsPositiveForH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals positive for schistosomal parasite eggs in urine.
        /// </summary>
        public static string SCHMapSurNumPosSchParasite {
            get {
                return ResourceManager.GetString("SCHMapSurNumPosSchParasite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals positive for haematuria in urine.
        /// </summary>
        public static string SCHSurNumberOfIndividualsPositiveForHaem {
            get {
                return ResourceManager.GetString("SCHSurNumberOfIndividualsPositiveForHaem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of individuals positive for schistosomal parasite eggs in urine.
        /// </summary>
        public static string SCHSurNumPosSchParasite {
            get {
                return ResourceManager.GetString("SCHSurNumPosSchParasite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paracetamol.
        /// </summary>
        public static string ScmDrpPara {
            get {
                return ResourceManager.GetString("ScmDrpPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Count.
        /// </summary>
        public static string ScmPhysicalCount {
            get {
                return ResourceManager.GetString("ScmPhysicalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theoretical Count.
        /// </summary>
        public static string ScmTheoreticalCount {
            get {
                return ResourceManager.GetString("ScmTheoreticalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Inventory.
        /// </summary>
        public static string ScmTypeOfInventory {
            get {
                return ResourceManager.GetString("ScmTypeOfInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregating level: Demography values from this level will total up to higher administrative units. Complete demography data needs to be entered for all of the units at this administrative level..
        /// </summary>
        public static string SettingsAggLevelDesc {
            get {
                return ResourceManager.GetString("SettingsAggLevelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting level: WHO and partner reports will automatically be generated for administrative units at this level. Typically this is the “District” or second administrative level..
        /// </summary>
        public static string SettingsReportingLevelDesc {
            get {
                return ResourceManager.GetString("SettingsReportingLevelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show redistricting events.
        /// </summary>
        public static string ShowRedistrictingEvents {
            get {
                return ResourceManager.GetString("ShowRedistrictingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All other data has been distributed between the new administrative units. Please click &quot;Next&quot; to review and make changes..
        /// </summary>
        public static string SplitConfirmReview {
            get {
                return ResourceManager.GetString("SplitConfirmReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup database before continuing.
        /// </summary>
        public static string SplittingBackup {
            get {
                return ResourceManager.GetString("SplittingBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click &quot;Next&quot; to backup your current database before continuing this process..
        /// </summary>
        public static string SplittingBackupMessage {
            get {
                return ResourceManager.GetString("SplittingBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When merging administrative units, data will be combined within the same year. How would you like to define the year?.
        /// </summary>
        public static string SplittingMergeYear {
            get {
                return ResourceManager.GetString("SplittingMergeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must allocate all SAEs to a new destination before continuing..
        /// </summary>
        public static string SplittingMustAllocateSaes {
            get {
                return ResourceManager.GetString("SplittingMustAllocateSaes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Percentages.
        /// </summary>
        public static string SplittingPercentages {
            get {
                return ResourceManager.GetString("SplittingPercentages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split SAEs.
        /// </summary>
        public static string SplittingSaes {
            get {
                return ResourceManager.GetString("SplittingSaes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey data from the parent districts was duplicated in all the daughter districts and should be reviewed..
        /// </summary>
        public static string SplittingSurveyWarning {
            get {
                return ResourceManager.GetString("SplittingSurveyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you finished entering all the administrative units for this level?.
        /// </summary>
        public static string StartUpFinishedAllUnits {
            get {
                return ResourceManager.GetString("StartUpFinishedAllUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-district.
        /// </summary>
        public static string SubDistrict {
            get {
                return ResourceManager.GetString("SubDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical cutoff decision.
        /// </summary>
        public static string TASCriticalCutoff {
            get {
                return ResourceManager.GetString("TASCriticalCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above treatment threshold - fail.
        /// </summary>
        public static string TASCutoffFail {
            get {
                return ResourceManager.GetString("TASCutoffFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below treatment threshold - pass.
        /// </summary>
        public static string TASCutoffPass {
            get {
                return ResourceManager.GetString("TASCutoffPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # 15+ year old adults surveyed.
        /// </summary>
        public static string TraMapSur15yo {
            get {
                return ResourceManager.GetString("TraMapSur15yo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # 1-9 year old children surveyed.
        /// </summary>
        public static string TraMapSur1to9yo {
            get {
                return ResourceManager.GetString("TraMapSur1to9yo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Trachoma Indicator.
        /// </summary>
        public static string TraMapSurActiveTrachomaIndicator {
            get {
                return ResourceManager.GetString("TraMapSurActiveTrachomaIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District-level MDA.
        /// </summary>
        public static string TraMapSurDistLevelMda {
            get {
                return ResourceManager.GetString("TraMapSurDistLevelMda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F&amp;E: % of children with clean faces.
        /// </summary>
        public static string TraMapSurFandE {
            get {
                return ResourceManager.GetString("TraMapSurFandE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Females 15+ years.
        /// </summary>
        public static string TraMapSurFemale15yo {
            get {
                return ResourceManager.GetString("TraMapSurFemale15yo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Females 40+ years.
        /// </summary>
        public static string TraMapSurFemale40yo {
            get {
                return ResourceManager.GetString("TraMapSurFemale40yo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male &amp; Female 15+ years.
        /// </summary>
        public static string TraMapSurMaleFemale15yo {
            get {
                return ResourceManager.GetString("TraMapSurMaleFemale15yo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male &amp; Female 40+ years.
        /// </summary>
        public static string TraMapSurMaleFemale40yo {
            get {
                return ResourceManager.GetString("TraMapSurMaleFemale40yo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No A required, consider F&amp;E.
        /// </summary>
        public static string TraMapSurNoAReq {
            get {
                return ResourceManager.GetString("TraMapSurNoAReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of clusters sampled.
        /// </summary>
        public static string TraMapSurNoClusters {
            get {
                return ResourceManager.GetString("TraMapSurNoClusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevalence of Active Trachoma (%TF).
        /// </summary>
        public static string TraMapSurPrevalenceActive {
            get {
                return ResourceManager.GetString("TraMapSurPrevalenceActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevalence of Trachoma Trichiasis (%TT).
        /// </summary>
        public static string TraMapSurPrevTt {
            get {
                return ResourceManager.GetString("TraMapSurPrevTt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-district level MDA.
        /// </summary>
        public static string TraMapSurSubDistMda {
            get {
                return ResourceManager.GetString("TraMapSurSubDistMda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery: 0.01% of population (year of survey).
        /// </summary>
        public static string TraMapSurSurgery01pop {
            get {
                return ResourceManager.GetString("TraMapSurSurgery01pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery: Number of TT cases in children &lt;15 years.
        /// </summary>
        public static string TraMapSurSurgeryNumTt {
            get {
                return ResourceManager.GetString("TraMapSurSurgeryNumTt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted MDA.
        /// </summary>
        public static string TraMapSurTargetedMda {
            get {
                return ResourceManager.GetString("TraMapSurTargetedMda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF-Alone.
        /// </summary>
        public static string TraMapSurTfAlone {
            get {
                return ResourceManager.GetString("TraMapSurTfAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF&amp;TI.
        /// </summary>
        public static string TraMapSurTfTi {
            get {
                return ResourceManager.GetString("TraMapSurTfTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TI-Alone.
        /// </summary>
        public static string TraMapSurTiAlone {
            get {
                return ResourceManager.GetString("TraMapSurTiAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT Indicator.
        /// </summary>
        public static string TraMapSurTtInd {
            get {
                return ResourceManager.GetString("TraMapSurTtInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District-level MDA.
        /// </summary>
        public static string TraSurDistLevel {
            get {
                return ResourceManager.GetString("TraSurDistLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-MDA surveillance.
        /// </summary>
        public static string TraSurPostMda {
            get {
                return ResourceManager.GetString("TraSurPostMda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-district level MDA.
        /// </summary>
        public static string TraSurSubDistLevel {
            get {
                return ResourceManager.GetString("TraSurSubDistLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted MDA.
        /// </summary>
        public static string TraSurTargetedMda {
            get {
                return ResourceManager.GetString("TraSurTargetedMda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trichiasis Surgeon Training.
        /// </summary>
        public static string TriTraining {
            get {
                return ResourceManager.GetString("TriTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLTR.
        /// </summary>
        public static string TriTrainingBltr {
            get {
                return ResourceManager.GetString("TriTrainingBltr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification.
        /// </summary>
        public static string TriTrainingCertification {
            get {
                return ResourceManager.GetString("TriTrainingCertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye care worker.
        /// </summary>
        public static string TriTrainingEyeCareWorker {
            get {
                return ResourceManager.GetString("TriTrainingEyeCareWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health worker.
        /// </summary>
        public static string TriTrainingHealthWorker {
            get {
                return ResourceManager.GetString("TriTrainingHealthWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgical method taught.
        /// </summary>
        public static string TriTrainingMethod {
            get {
                return ResourceManager.GetString("TriTrainingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New surgeon.
        /// </summary>
        public static string TriTrainingNewSurgeon {
            get {
                return ResourceManager.GetString("TriTrainingNewSurgeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT Surgeon Qualifications.
        /// </summary>
        public static string TriTrainingQualifications {
            get {
                return ResourceManager.GetString("TriTrainingQualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresher.
        /// </summary>
        public static string TriTrainingRefresher {
            get {
                return ResourceManager.GetString("TriTrainingRefresher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of TT Surgeon (the 2 indicators below should be associated with the surgeon name).
        /// </summary>
        public static string TriTrainingSurgeonName {
            get {
                return ResourceManager.GetString("TriTrainingSurgeonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabut.
        /// </summary>
        public static string TriTrainingTrabut {
            get {
                return ResourceManager.GetString("TriTrainingTrabut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of TT Surgeon Trainer.
        /// </summary>
        public static string TriTrainingTrainerName {
            get {
                return ResourceManager.GetString("TriTrainingTrainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of training.
        /// </summary>
        public static string TriTrainingType {
            get {
                return ResourceManager.GetString("TriTrainingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was the surgeon certified using WHO guidelines?.
        /// </summary>
        public static string TriTrainingWasCertified {
            get {
                return ResourceManager.GetString("TriTrainingWasCertified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT AIOs.
        /// </summary>
        public static string TtAios {
            get {
                return ResourceManager.GetString("TtAios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2014 Annual Intervention Objective.
        /// </summary>
        public static string TtAios2014 {
            get {
                return ResourceManager.GetString("TtAios2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015 Annual Intervention Objective.
        /// </summary>
        public static string TtAios2015 {
            get {
                return ResourceManager.GetString("TtAios2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016 Annual Intervention Objective.
        /// </summary>
        public static string TtAios2016 {
            get {
                return ResourceManager.GetString("TtAios2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2017 Annual Intervention Objective.
        /// </summary>
        public static string TtAios2017 {
            get {
                return ResourceManager.GetString("TtAios2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018 Annual Intervention Objective.
        /// </summary>
        public static string TtAios2018 {
            get {
                return ResourceManager.GetString("TtAios2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019 Annual Intervention Objective.
        /// </summary>
        public static string TtAios2019 {
            get {
                return ResourceManager.GetString("TtAios2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020 Annual Intervention Objective.
        /// </summary>
        public static string TtAios2020 {
            get {
                return ResourceManager.GetString("TtAios2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be sure to update disease distribution as appropriate incorporating the results of this survey.
        /// </summary>
        public static string UpdateDdAfterSavingSurvey {
            get {
                return ResourceManager.GetString("UpdateDdAfterSavingSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Disease Distribution.
        /// </summary>
        public static string UpdateDdAfterSavingSurveyTitle {
            get {
                return ResourceManager.GetString("UpdateDdAfterSavingSurveyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is now updating. This process might take a few minutes..
        /// </summary>
        public static string UpdatingMightTake {
            get {
                return ResourceManager.GetString("UpdatingMightTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between {0} and {1}.
        /// </summary>
        public static string ValidNumberRange {
            get {
                return ResourceManager.GetString("ValidNumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/edit.
        /// </summary>
        public static string ViewEdit {
            get {
                return ResourceManager.GetString("ViewEdit", resourceCulture);
            }
        }
    }
}
