//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nada.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nada.Globalization.NewKeys", typeof(NewKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this area under PTS (post treatment surveillance)?.
        /// </summary>
        public static string DDPTS {
            get {
                return ResourceManager.GetString("DDPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # female SAC treated.
        /// </summary>
        public static string IntvFemaleSac {
            get {
                return ResourceManager.GetString("IntvFemaleSac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # male SAC treated.
        /// </summary>
        public static string IntvMaleSac {
            get {
                return ResourceManager.GetString("IntvMaleSac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of site.
        /// </summary>
        public static string SchMappingTypeOfSite {
            get {
                return ResourceManager.GetString("SchMappingTypeOfSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of most recent PC.
        /// </summary>
        public static string SchSentinelDatePc {
            get {
                return ResourceManager.GetString("SchSentinelDatePc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of site.
        /// </summary>
        public static string SchSentinelTypeSite {
            get {
                return ResourceManager.GetString("SchSentinelTypeSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of site.
        /// </summary>
        public static string SthMappingTypeSite {
            get {
                return ResourceManager.GetString("SthMappingTypeSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of most recent PC.
        /// </summary>
        public static string SthSpotCheckDatePc {
            get {
                return ResourceManager.GetString("SthSpotCheckDatePc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of site.
        /// </summary>
        public static string SthSpotCheckTypeSite {
            get {
                return ResourceManager.GetString("SthSpotCheckTypeSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual non-response rate - total (%).
        /// </summary>
        public static string TasActualNonResponse {
            get {
                return ResourceManager.GetString("TasActualNonResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of LF endemic districts surrounding this Evaluation Unit that haven&apos;t started treatment.
        /// </summary>
        public static string TasNumNoTreatment {
            get {
                return ResourceManager.GetString("TasNumNoTreatment", resourceCulture);
            }
        }
    }
}
