//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nada.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nada.Globalization.NewKeys", typeof(NewKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated {0} forms!.
        /// </summary>
        public static string ImportUpdateSuccess {
            get {
                return ResourceManager.GetString("ImportUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date redistricting occurred.
        /// </summary>
        public static string RedistrictDate {
            get {
                return ResourceManager.GetString("RedistrictDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging rule.
        /// </summary>
        public static string RedistrictRuleMerge {
            get {
                return ResourceManager.GetString("RedistrictRuleMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting rule.
        /// </summary>
        public static string RedistrictRuleSplit {
            get {
                return ResourceManager.GetString("RedistrictRuleSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split/combine rule.
        /// </summary>
        public static string RedistrictRuleSplitCombine {
            get {
                return ResourceManager.GetString("RedistrictRuleSplitCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Redistricted, original administrative units survey occured in: {0}.
        /// </summary>
        public static string RedistrictSurveyNote {
            get {
                return ResourceManager.GetString("RedistrictSurveyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must assign all rules before continuing..
        /// </summary>
        public static string SplittingMustAllocateRules {
            get {
                return ResourceManager.GetString("SplittingMustAllocateRules", resourceCulture);
            }
        }
    }
}
