//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nada.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewNewKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewNewKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nada.Globalization.NewNewKeys", typeof(NewNewKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new form.
        /// </summary>
        public static string CreateNewForm {
            get {
                return ResourceManager.GetString("CreateNewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating update files.
        /// </summary>
        public static string CreatingUpdateFiles {
            get {
                return ResourceManager.GetString("CreatingUpdateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop administrative units to reorder.
        /// </summary>
        public static string DragToReorder {
            get {
                return ResourceManager.GetString("DragToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit administrative unit &gt;.
        /// </summary>
        public static string EditAdministrativeUnit {
            get {
                return ResourceManager.GetString("EditAdministrativeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form type.
        /// </summary>
        public static string IndFormType {
            get {
                return ResourceManager.GetString("IndFormType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes have been validated, please make sure there are no errors..
        /// </summary>
        public static string IndicatorUpdatesValidated {
            get {
                return ResourceManager.GetString("IndicatorUpdatesValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator management.
        /// </summary>
        public static string MenuIndicatorManagement {
            get {
                return ResourceManager.GetString("MenuIndicatorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order administrative units.
        /// </summary>
        public static string MenuReorderAdminLevel {
            get {
                return ResourceManager.GetString("MenuReorderAdminLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date redistricting documented in database.
        /// </summary>
        public static string RedistEventDate {
            get {
                return ResourceManager.GetString("RedistEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Administrator.
        /// </summary>
        public static string RoleDbAdmin {
            get {
                return ResourceManager.GetString("RoleDbAdmin", resourceCulture);
            }
        }
    }
}
