//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nada.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nada.Globalization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About National Database Template.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/remove indicators &gt;.
        /// </summary>
        public static string AddIndicatorLink {
            get {
                return ResourceManager.GetString("AddIndicatorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New....
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new disease &gt;.
        /// </summary>
        public static string AddNewDiseaseLink {
            get {
                return ResourceManager.GetString("AddNewDiseaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new intervention type....
        /// </summary>
        public static string AddNewIntvType {
            get {
                return ResourceManager.GetString("AddNewIntvType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new survey type....
        /// </summary>
        public static string AddNewSurveyTypeLink {
            get {
                return ResourceManager.GetString("AddNewSurveyTypeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Funder/Partner &gt;.
        /// </summary>
        public static string AddPartnerLink {
            get {
                return ResourceManager.GetString("AddPartnerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age range.
        /// </summary>
        public static string AgeRange {
            get {
                return ResourceManager.GetString("AgeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregated by.
        /// </summary>
        public static string AggregatedBy {
            get {
                return ResourceManager.GetString("AggregatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALB.
        /// </summary>
        public static string ALB {
            get {
                return ResourceManager.GetString("ALB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTD National Database.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string AuditCreated {
            get {
                return ResourceManager.GetString("AuditCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string AuditUpdated {
            get {
                return ResourceManager.GetString("AuditUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available reports.
        /// </summary>
        public static string AvailableReports {
            get {
                return ResourceManager.GetString("AvailableReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline.
        /// </summary>
        public static string Baseline {
            get {
                return ResourceManager.GetString("Baseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugia spp..
        /// </summary>
        public static string Brugiaspp {
            get {
                return ResourceManager.GetString("Brugiaspp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual agent.
        /// </summary>
        public static string CasualAgent {
            get {
                return ResourceManager.GetString("CasualAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Admin Levels.
        /// </summary>
        public static string ChooseAdminLevels {
            get {
                return ResourceManager.GetString("ChooseAdminLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2013. All rights reserved..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Import File.
        /// </summary>
        public static string CreateImportFile {
            get {
                return ResourceManager.GetString("CreateImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Import File....
        /// </summary>
        public static string CreatingImportFileStatus {
            get {
                return ResourceManager.GetString("CreatingImportFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Indicator.
        /// </summary>
        public static string CustomIndicator {
            get {
                return ResourceManager.GetString("CustomIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom indicator name.
        /// </summary>
        public static string CustomIndicatorName {
            get {
                return ResourceManager.GetString("CustomIndicatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Indicators.
        /// </summary>
        public static string CustomIndicators {
            get {
                return ResourceManager.GetString("CustomIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Report.
        /// </summary>
        public static string CustomReport {
            get {
                return ResourceManager.GetString("CustomReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Report Builder.
        /// </summary>
        public static string CustomReportBuilder {
            get {
                return ResourceManager.GetString("CustomReportBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard/Getting Stared Placeholder.
        /// </summary>
        public static string DashboardPlaceholder {
            get {
                return ResourceManager.GetString("DashboardPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type.
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-14 days.
        /// </summary>
        public static string days14 {
            get {
                return ResourceManager.GetString("days14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-2 days.
        /// </summary>
        public static string days2 {
            get {
                return ResourceManager.GetString("days2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demography.
        /// </summary>
        public static string Demography {
            get {
                return ResourceManager.GetString("Demography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Distribution.
        /// </summary>
        public static string DiseaseDistribution {
            get {
                return ResourceManager.GetString("DiseaseDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Distribution: PC interventions.
        /// </summary>
        public static string DiseaseEndemicity {
            get {
                return ResourceManager.GetString("DiseaseEndemicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseases.
        /// </summary>
        public static string Diseases {
            get {
                return ResourceManager.GetString("Diseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select diseases targeted..
        /// </summary>
        public static string DiseasesRequired {
            get {
                return ResourceManager.GetString("DiseasesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesease Distribution: Trichiasis Surgery.
        /// </summary>
        public static string DiseaseTrichiasis {
            get {
                return ResourceManager.GetString("DiseaseTrichiasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year disease distribution information applies to.
        /// </summary>
        public static string DiseaseYear {
            get {
                return ResourceManager.GetString("DiseaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit report options.
        /// </summary>
        public static string EditReportOptions {
            get {
                return ResourceManager.GetString("EditReportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Eligible females targeted.
        /// </summary>
        public static string EligibleFemalesTargeted {
            get {
                return ResourceManager.GetString("EligibleFemalesTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Eligible males targeted.
        /// </summary>
        public static string EligibleMalesTargeted {
            get {
                return ResourceManager.GetString("EligibleMalesTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 - Not endemic above treatment threshold.
        /// </summary>
        public static string End0 {
            get {
                return ResourceManager.GetString("End0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Endemic above treatment threshold.
        /// </summary>
        public static string End1 {
            get {
                return ResourceManager.GetString("End1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 - Achieved stopping MDA criteria.
        /// </summary>
        public static string End100 {
            get {
                return ResourceManager.GetString("End100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date of MDA.
        /// </summary>
        public static string EndDateMda {
            get {
                return ResourceManager.GetString("EndDateMda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date of survey.
        /// </summary>
        public static string EndDateSurvey {
            get {
                return ResourceManager.GetString("EndDateSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M - Not mapped.
        /// </summary>
        public static string EndM {
            get {
                return ResourceManager.GetString("EndM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NS - Not mapped but not suspected.
        /// </summary>
        public static string EndNS {
            get {
                return ResourceManager.GetString("EndNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending - Awaiting TAS implementation/results.
        /// </summary>
        public static string EndPending {
            get {
                return ResourceManager.GetString("EndPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new.
        /// </summary>
        public static string EnterNew {
            get {
                return ResourceManager.GetString("EnterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New....
        /// </summary>
        public static string EnterNewLink {
            get {
                return ResourceManager.GetString("EnterNewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epi coverage.
        /// </summary>
        public static string EpiCoverage {
            get {
                return ResourceManager.GetString("EpiCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number examined.
        /// </summary>
        public static string Examined {
            get {
                return ResourceManager.GetString("Examined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Females treated proportion.
        /// </summary>
        public static string FemalesCoverage {
            get {
                return ResourceManager.GetString("FemalesCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than 1 month.
        /// </summary>
        public static string GreaterThanMonth {
            get {
                return ResourceManager.GetString("GreaterThanMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICT.
        /// </summary>
        public static string ICT {
            get {
                return ResourceManager.GetString("ICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        public static string ImportAction {
            get {
                return ResourceManager.GetString("ImportAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import new data.
        /// </summary>
        public static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was an incorrect format or had no data.
        /// </summary>
        public static string ImportNoDataError {
            get {
                return ResourceManager.GetString("ImportNoDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added {0} new records!.
        /// </summary>
        public static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervention Information.
        /// </summary>
        public static string InterventionInfo {
            get {
                return ResourceManager.GetString("InterventionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interventions.
        /// </summary>
        public static string Interventions {
            get {
                return ResourceManager.GetString("Interventions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervention type.
        /// </summary>
        public static string InterventionType {
            get {
                return ResourceManager.GetString("InterventionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iota Ink.
        /// </summary>
        public static string IotaInk {
            get {
                return ResourceManager.GetString("IotaInk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVM.
        /// </summary>
        public static string IVM {
            get {
                return ResourceManager.GetString("IVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVM + ALB Intervention.
        /// </summary>
        public static string IvmAlbIntervention {
            get {
                return ResourceManager.GetString("IvmAlbIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated:.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leporsy.
        /// </summary>
        public static string Leporsy {
            get {
                return ResourceManager.GetString("Leporsy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of implementation.
        /// </summary>
        public static string LevelImplementation {
            get {
                return ResourceManager.GetString("LevelImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF.
        /// </summary>
        public static string LF {
            get {
                return ResourceManager.GetString("LF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF Disease Distribution....
        /// </summary>
        public static string LFDiseaseDistribution {
            get {
                return ResourceManager.GetString("LFDiseaseDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF Hydrocele Morbidity.
        /// </summary>
        public static string LFHydroceleMorbidity {
            get {
                return ResourceManager.GetString("LFHydroceleMorbidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF Lymphedema Morbidity.
        /// </summary>
        public static string LFLymphedemaMorbidity {
            get {
                return ResourceManager.GetString("LFLymphedemaMorbidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF MDA.
        /// </summary>
        public static string LFMDA {
            get {
                return ResourceManager.GetString("LFMDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF Population Information.
        /// </summary>
        public static string LFPopulationInformation {
            get {
                return ResourceManager.GetString("LFPopulationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF Sentinel-Spot Check Survey Import.
        /// </summary>
        public static string LfSentinelImport {
            get {
                return ResourceManager.GetString("LfSentinelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a location..
        /// </summary>
        public static string LocationRequired {
            get {
                return ResourceManager.GetString("LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location &gt;.
        /// </summary>
        public static string LocationSelectLink {
            get {
                return ResourceManager.GetString("LocationSelectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in..
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Males treated proportion.
        /// </summary>
        public static string MalesCoverage {
            get {
                return ResourceManager.GetString("MalesCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping.
        /// </summary>
        public static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDAs.
        /// </summary>
        public static string MDAs {
            get {
                return ResourceManager.GetString("MDAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean density.
        /// </summary>
        public static string MeanDensity {
            get {
                return ResourceManager.GetString("MeanDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mf.
        /// </summary>
        public static string Mf {
            get {
                return ResourceManager.GetString("Mf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string MfCount {
            get {
                return ResourceManager.GetString("MfCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Mf Load.
        /// </summary>
        public static string MfLoad {
            get {
                return ResourceManager.GetString("MfLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid-term.
        /// </summary>
        public static string Midterm {
            get {
                return ResourceManager.GetString("Midterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring and Training.
        /// </summary>
        public static string MonitoringTraining {
            get {
                return ResourceManager.GetString("MonitoringTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid date (mm/dd/yyyy).
        /// </summary>
        public static string MustBeDate {
            get {
                return ResourceManager.GetString("MustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number.
        /// </summary>
        public static string MustBeNumber {
            get {
                return ResourceManager.GetString("MustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new data.
        /// </summary>
        public static string NewData {
            get {
                return ResourceManager.GetString("NewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        public static string NewLink {
            get {
                return ResourceManager.GetString("NewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number with nonresponse.
        /// </summary>
        public static string Nonresponsive {
            get {
                return ResourceManager.GetString("Nonresponsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet resolved.
        /// </summary>
        public static string NotResolved {
            get {
                return ResourceManager.GetString("NotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Adults targeted.
        /// </summary>
        public static string NumAdultsTargeted {
            get {
                return ResourceManager.GetString("NumAdultsTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Adults treated.
        /// </summary>
        public static string NumAdultsTreated {
            get {
                return ResourceManager.GetString("NumAdultsTreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Individuals at risk.
        /// </summary>
        public static string NumAtRisk {
            get {
                return ResourceManager.GetString("NumAtRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Eligible females treated.
        /// </summary>
        public static string NumEligibleFemalesTreated {
            get {
                return ResourceManager.GetString("NumEligibleFemalesTreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Eligible males treated.
        /// </summary>
        public static string NumEligibleMalesTreated {
            get {
                return ResourceManager.GetString("NumEligibleMalesTreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number eligible individuals targeted.
        /// </summary>
        public static string NumEligibleTargeted {
            get {
                return ResourceManager.GetString("NumEligibleTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Eligible individuals treated.
        /// </summary>
        public static string NumEligibleTreated {
            get {
                return ResourceManager.GetString("NumEligibleTreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # PSAC targeted.
        /// </summary>
        public static string NumPsacTargeted {
            get {
                return ResourceManager.GetString("NumPsacTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # PSAC treated.
        /// </summary>
        public static string NumPsacTreated {
            get {
                return ResourceManager.GetString("NumPsacTreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Serious adverse events reported.
        /// </summary>
        public static string NumSacReported {
            get {
                return ResourceManager.GetString("NumSacReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # SAC targeted.
        /// </summary>
        public static string NumSacTargeted {
            get {
                return ResourceManager.GetString("NumSacTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # SAC treated.
        /// </summary>
        public static string NumSacTreated {
            get {
                return ResourceManager.GetString("NumSacTreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of total, targeted for oncho.
        /// </summary>
        public static string NumTargetedOncho {
            get {
                return ResourceManager.GetString("NumTargetedOncho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of total, treated for oncho.
        /// </summary>
        public static string NumTreatedOncho {
            get {
                return ResourceManager.GetString("NumTreatedOncho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Persons treated with TEO.
        /// </summary>
        public static string NumTreatedTeo {
            get {
                return ResourceManager.GetString("NumTreatedTeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Persons treated with Zx tablets.
        /// </summary>
        public static string NumTreatedZx {
            get {
                return ResourceManager.GetString("NumTreatedZx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Persons treated with Zx POS.
        /// </summary>
        public static string NumTreatedZxPos {
            get {
                return ResourceManager.GetString("NumTreatedZxPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops,there was a problem!.
        /// </summary>
        public static string OopsProblem {
            get {
                return ResourceManager.GetString("OopsProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funders/Partners.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        public static string PC {
            get {
                return ResourceManager.GetString("PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCs targeted.
        /// </summary>
        public static string PcsTargeted {
            get {
                return ResourceManager.GetString("PcsTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % positive.
        /// </summary>
        public static string PercentPositive {
            get {
                return ResourceManager.GetString("PercentPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select....
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population.
        /// </summary>
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number positive.
        /// </summary>
        public static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-MDA Surveillance TAS I.
        /// </summary>
        public static string PostMDAI {
            get {
                return ResourceManager.GetString("PostMDAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-MDA Surveillance TAS II.
        /// </summary>
        public static string PostMDAII {
            get {
                return ResourceManager.GetString("PostMDAII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAS eligibility (Pre-TAS).
        /// </summary>
        public static string PreTAS {
            get {
                return ResourceManager.GetString("PreTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program coverage.
        /// </summary>
        public static string ProgramCoverage {
            get {
                return ResourceManager.GetString("ProgramCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSAC coverage.
        /// </summary>
        public static string PsacCoverage {
            get {
                return ResourceManager.GetString("PsacCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select locations.
        /// </summary>
        public static string ReportLocations {
            get {
                return ResourceManager.GetString("ReportLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report options.
        /// </summary>
        public static string ReportOptions {
            get {
                return ResourceManager.GetString("ReportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round number.
        /// </summary>
        public static string RoundNumber {
            get {
                return ResourceManager.GetString("RoundNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # PC rounds/year currently implemented.
        /// </summary>
        public static string RoundsCurrentlyImplemented {
            get {
                return ResourceManager.GetString("RoundsCurrentlyImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rounds of PC  completed prior to survey implementation.
        /// </summary>
        public static string RoundsMda {
            get {
                return ResourceManager.GetString("RoundsMda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of treatment rounds planned for the year.
        /// </summary>
        public static string RoundsPlannedYear {
            get {
                return ResourceManager.GetString("RoundsPlannedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # PC rounds/year recommended by WHO guidelines.
        /// </summary>
        public static string RoundsRecommendedByWho {
            get {
                return ResourceManager.GetString("RoundsRecommendedByWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAC coverage.
        /// </summary>
        public static string SacCoverage {
            get {
                return ResourceManager.GetString("SacCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number sampled.
        /// </summary>
        public static string Sampled {
            get {
                return ResourceManager.GetString("Sampled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target sample size.
        /// </summary>
        public static string SampleSize {
            get {
                return ResourceManager.GetString("SampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a report category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select indicators.
        /// </summary>
        public static string SelectIndicators {
            get {
                return ResourceManager.GetString("SelectIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel.
        /// </summary>
        public static string Sentinel {
            get {
                return ResourceManager.GetString("Sentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel Site.
        /// </summary>
        public static string SentinelSite {
            get {
                return ResourceManager.GetString("SentinelSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel sites.
        /// </summary>
        public static string SentinelSites {
            get {
                return ResourceManager.GetString("SentinelSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel/Spot Check Site Survey.
        /// </summary>
        public static string SentinelSpotSurvey {
            get {
                return ResourceManager.GetString("SentinelSpotSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of site.
        /// </summary>
        public static string SiteType {
            get {
                return ResourceManager.GetString("SiteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort order.
        /// </summary>
        public static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot Check.
        /// </summary>
        public static string SpotCheck {
            get {
                return ResourceManager.GetString("SpotCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot Check Site Name.
        /// </summary>
        public static string SpotCheckSiteName {
            get {
                return ResourceManager.GetString("SpotCheckSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date of MDA.
        /// </summary>
        public static string StartDateMda {
            get {
                return ResourceManager.GetString("StartDateMda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date of survey.
        /// </summary>
        public static string StartDateSurvey {
            get {
                return ResourceManager.GetString("StartDateSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock out during MDA?.
        /// </summary>
        public static string StockOut {
            get {
                return ResourceManager.GetString("StockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock out drug.
        /// </summary>
        public static string StockOutDrug {
            get {
                return ResourceManager.GetString("StockOutDrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of stock out.
        /// </summary>
        public static string StockOutLength {
            get {
                return ResourceManager.GetString("StockOutLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop-MDA TAS.
        /// </summary>
        public static string StopMDATAS {
            get {
                return ResourceManager.GetString("StopMDATAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Information.
        /// </summary>
        public static string SurveyInformation {
            get {
                return ResourceManager.GetString("SurveyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey name.
        /// </summary>
        public static string SurveyName {
            get {
                return ResourceManager.GetString("SurveyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        public static string Surveys {
            get {
                return ResourceManager.GetString("Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey type.
        /// </summary>
        public static string SurveyType {
            get {
                return ResourceManager.GetString("SurveyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAS.
        /// </summary>
        public static string TAS {
            get {
                return ResourceManager.GetString("TAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective of planned TAS.
        /// </summary>
        public static string TasObjective {
            get {
                return ResourceManager.GetString("TasObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month/Year of planned TAS.
        /// </summary>
        public static string TasYearMonth {
            get {
                return ResourceManager.GetString("TasYearMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test type.
        /// </summary>
        public static string TestType {
            get {
                return ResourceManager.GetString("TestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey timing.
        /// </summary>
        public static string TimingType {
            get {
                return ResourceManager.GetString("TimingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate intervention goal for active trachoma.
        /// </summary>
        public static string TrachomaGoal {
            get {
                return ResourceManager.GetString("TrachomaGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month/Year of planned trachoma impact survey.
        /// </summary>
        public static string TrachomaImpactYearMonth {
            get {
                return ResourceManager.GetString("TrachomaImpactYearMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Report.
        /// </summary>
        public static string TreatmentReport {
            get {
                return ResourceManager.GetString("TreatmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trichiasis surgery backlog.
        /// </summary>
        public static string TrichiasisSurgeryBacklog {
            get {
                return ResourceManager.GetString("TrichiasisSurgeryBacklog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate intervention goal for trichiasis surgery.
        /// </summary>
        public static string TrichiasisSurgeryGoal {
            get {
                return ResourceManager.GetString("TrichiasisSurgeryGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update completed.
        /// </summary>
        public static string UpdateComplete {
            get {
                return ResourceManager.GetString("UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update found, please ensure internet access.
        /// </summary>
        public static string UpdateException {
            get {
                return ResourceManager.GetString("UpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update found.
        /// </summary>
        public static string UpdateNone {
            get {
                return ResourceManager.GetString("UpdateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        public static string UpdatesCheck {
            get {
                return ResourceManager.GetString("UpdatesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the errors before continuing..
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude must be between -90° and 90°.
        /// </summary>
        public static string ValidLatitude {
            get {
                return ResourceManager.GetString("ValidLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude must be between -180° and 180°.
        /// </summary>
        public static string ValidLongitude {
            get {
                return ResourceManager.GetString("ValidLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between 0 and 20.
        /// </summary>
        public static string ValidRoundsMda {
            get {
                return ResourceManager.GetString("ValidRoundsMda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid year (1900-2050).
        /// </summary>
        public static string ValidYear {
            get {
                return ResourceManager.GetString("ValidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vectors.
        /// </summary>
        public static string Vectors {
            get {
                return ResourceManager.GetString("Vectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help.
        /// </summary>
        public static string ViewHelp {
            get {
                return ResourceManager.GetString("ViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View reports.
        /// </summary>
        public static string Viewreports {
            get {
                return ResourceManager.GetString("Viewreports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W. bancrofti.
        /// </summary>
        public static string Wbancrofti {
            get {
                return ResourceManager.GetString("Wbancrofti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W. bancrofti &amp; Brugia spp..
        /// </summary>
        public static string WbancroftiBrugiaspp {
            get {
                return ResourceManager.GetString("WbancroftiBrugiaspp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-4 weeks.
        /// </summary>
        public static string weeks4 {
            get {
                return ResourceManager.GetString("weeks4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1x/year.
        /// </summary>
        public static string xyear1 {
            get {
                return ResourceManager.GetString("xyear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x/year.
        /// </summary>
        public static string xyear2 {
            get {
                return ResourceManager.GetString("xyear2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of first round of MDA (Year).
        /// </summary>
        public static string YearFirstRoundPc {
            get {
                return ResourceManager.GetString("YearFirstRoundPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year PC Started.
        /// </summary>
        public static string YearPcStarted {
            get {
                return ResourceManager.GetString("YearPcStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year determined that achieved criteria for stopping PC.
        /// </summary>
        public static string YearStoppingPc {
            get {
                return ResourceManager.GetString("YearStoppingPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year determined that achieved criteria for stopping PC (lower levels).
        /// </summary>
        public static string YearStoppingPcLower {
            get {
                return ResourceManager.GetString("YearStoppingPcLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No.
        /// </summary>
        public static string YesNo {
            get {
                return ResourceManager.GetString("YesNo", resourceCulture);
            }
        }
    }
}
